name: RareItems4
main: com.lonelymc.ri4.bukkit.RareItems4Plugin
version: '4.0.1a'
load: STARTUP
database: false
softdepend: [Vault]
description: Rare Items 4
commands:
    ri:
      description: RareItems commands
    hat:
      description: put an item on your head
permissions:
  ri4.wi:
    description: Can view properties and their recipes
    default: true
  ri4.admin.logs:
    description: Will see error summaries in-game
    default: false
  ri4.admin.recipe:
    description: Can edit property recipes
    default: false
  ri4.admin.craft:
    description: Can add item properties to items
    default: false
  ri4.admin.essence:
    description: Can create essences
    default: false