name: RareItems4
main: com.lonelymc.ri4.bukkit.RareItems4Plugin
version: '4.0a'
load: STARTUP
database: false
softdepend: [Vault]
description: Rare Items 4
commands:
    ri:
      description: RareItems commands
    hat:
      description: put an item on your head
permissions: 
# All
  ri4.tester:
    description: Permission to test ALL the things
    default: false
  ri4.admin.logs:
    description: Will see error summaries in-game
    default: false